const $=id=>document.getElementById(id), main=$('main');
const titles={pose:'看見我的動作',count:'坐著舉舉手',still:'動一動提醒',video:'預錄影片觀察'};
const defaults={visibility:.6,up:100,down:40,hold:400,smooth:5,side:'left',seconds:30,motion:.08,cancel:5,voice:true};
let p={...defaults},stage='home',detector=null,modelPromise=null,stream=null,running=false,loading=false,frameId=0,session=0,lastFrame=-1,lastInference=0,lastClock=-1,fileURL=null,tracking=false,wasTracking=null,observations=[],storageOK=true,lastPoints=null,lastScale=0;
let counter=new MotionLogic.Counter(p),still=new MotionLogic.Stillness(p),fall=new MotionLogic.Fall(),lostLogged=false;
try{observations=JSON.parse(localStorage.getItem('motion-observations-v1')||'[]');if(!Array.isArray(observations))observations=[];}catch{storageOK=false;}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<span class="step-icon" aria-hidden="true">${n}</span>`;
function notice(text){$('notice').textContent=text;}
function speak(text){if(p.voice&&'speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='zh-TW';u.rate=.85;speechSynthesis.speak(u);}}
function log(kind,note){observations.push({time:new Date().toISOString(),stage,kind,note,parameters:{...p}});try{localStorage.setItem('motion-observations-v1',JSON.stringify(observations));storageOK=true;}catch{storageOK=false;notice('測試紀錄尚未保存，請先下載 CSV 備份。');}refreshLogs();}
function refreshLogs(){if($('logs'))$('logs').innerHTML=observations.slice(-8).reverse().map(x=>`<li><strong>${esc(x.kind)}</strong> · ${new Date(x.time).toLocaleTimeString('zh-TW')}<br>${esc(x.note)}</li>`).join('')||'<li>還沒有測試紀錄。</li>';if($('log-count'))$('log-count').textContent=`共 ${observations.length} 筆${storageOK?'，已存在這個瀏覽器':'，尚未完整保存'}`;}
function resetLogic(){counter=new MotionLogic.Counter(p);still=new MotionLogic.Stillness(p);fall=new MotionLogic.Fall();tracking=false;wasTracking=null;lastPoints=null;lastClock=-1;}
function stopMedia(){session++;loading=false;running=false;cancelAnimationFrame(frameId);if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}const v=$('video');if(v){v.pause();v.srcObject=null;}if('speechSynthesis'in window)speechSynthesis.cancel();if($('camera'))$('camera').classList.remove('running');if($('placeholder'))$('placeholder').hidden=false;if($('start')){$('start').disabled=false;$('start').textContent='開啟攝影機';}if($('stop'))$('stop').disabled=true;if($('alert'))$('alert').hidden=true;resetLogic();}
function go(next){stopMedia();if(fileURL){URL.revokeObjectURL(fileURL);fileURL=null;}stage=next;notice('');render();window.scrollTo(0,0);main.querySelector('h1').focus();}
$('home').onclick=()=>go('home');
function render(){
 if(stage==='home'){main.innerHTML=`<div class="eyebrow">看見動作，慢慢練習。</div><h1 tabindex="-1">一起動動手</h1><p class="lead">坐穩、放鬆，選一個活動開始。</p><div class="home-grid">${[['pose','01','第 11 週','看見我的動作','先確認鏡頭看得清楚'],['count','02','第 12 週','坐著舉舉手','抬起、放下，完成一次'],['still','03','第 13 週','動一動提醒','一段時間沒動，溫柔提醒']].map(([s,n,w,t,d])=>`<button class="nav-card" data-stage="${s}">${icon(n)}<span><span class="week">${w}</span><strong>${t}</strong><small>${d}</small></span><span class="arrow">›</span></button>`).join('')}</div><details class="settings"><summary>教師示範：預錄影片</summary><p class="hint">第 13 週以事先準備的影片觀察事件。不要求現場做跌倒動作。</p><button class="secondary full" data-stage="video">開啟影片觀察</button></details>${logPanel()}`;bind();return;}
 const videoMode=stage==='video';
 const steps={pose:'讓頭、肩膀、手肘與腰部都進入畫面。光線要充足，手機固定不晃動。',count:'坐穩，先把手放下。向側邊抬高手臂，再慢慢放下，完成一個來回。',still:'坐穩後開啟鏡頭。畫面中的上半身持續沒明顯移動，才會開始提醒。',video:'選擇教師準備的影片。偵測規則只用於課堂觀察，不代表能可靠判斷跌倒。'};
 main.innerHTML=`<div class="stage-head"><div><div class="eyebrow">${stage==='pose'?'第 11 週・看見骨架':stage==='count'?'第 12 週・動作計次':'第 13 週・事件觀察'}</div><h1 tabindex="-1">${titles[stage]}</h1></div><button class="quiet" data-stage="home">換活動</button></div><p class="guide">${steps[stage]}</p><div id="camera" class="camera ${videoMode?'':'mirrored'}"><video id="video" playsinline ${videoMode?'controls':'muted'}></video><canvas id="overlay"></canvas><div class="camera-placeholder" id="placeholder"><span aria-hidden="true">◎</span>${videoMode?'選擇一段預錄影片':'按下方按鈕，開啟攝影機'}<small>影像不會上傳</small></div></div><div id="tracking" class="status-line" role="status">${videoMode?'尚未載入影片':'鏡頭尚未開啟'}</div>${videoMode?`<label class="file-label">選擇預錄影片<input id="file" type="file" accept="video/*"></label><button class="primary full" id="play" disabled>播放／繼續</button><p class="small-note">暫停或拖曳影片會重設事件判斷。示範條件：身體中心快速下移、軀幹傾斜並持續一段時間。</p>`:`<div class="button-row"><button class="primary" id="start">開啟攝影機</button><button class="secondary" id="stop" disabled>停止</button></div>`}${metrics()}<div id="alert" class="alert" hidden><strong id="alert-title">要不要稍微動一動？</strong><p id="alert-text"></p><button class="secondary full" id="cancel-alert">我有在動，取消提醒</button></div>${stage==='count'?'<button class="secondary full" id="reset-count">次數歸零</button>':''}${settingsPanel()}${logPanel()}`;
 bind();refreshLogs();
}
function metrics(){if(stage==='pose')return '<div class="metrics"><div class="metric"><small>關鍵點可見度</small><strong id="quality">—</strong></div><div class="metric"><small>畫面狀態</small><strong id="pose-status">未開始</strong></div></div><p class="hint">可見度是模型估計，不是辨識準確率。</p>';
 if(stage==='count')return '<div class="metrics"><div class="metric wide"><small>完成的來回</small><strong id="count">0 <span>次</span></strong></div><div class="metric"><small>抬手角度</small><strong id="arm-angle">—</strong></div><div class="metric"><small>手肘角度</small><strong id="elbow-angle">—</strong></div></div><div id="action" class="status-line">先放下手，再抬起。</div>';
 if(stage==='still')return '<div class="metrics"><div class="metric wide"><small>上半身未明顯移動</small><strong id="idle">0 <span>秒</span></strong><progress id="progress" value="0" max="30"></progress></div></div><p class="hint">預設 30 秒是課堂示範。這裡偵測上半身位移，不會判斷是否真的坐著。</p>';
 return '<div class="metrics"><div class="metric"><small>軀幹傾斜</small><strong id="tilt">—</strong></div><div class="metric"><small>觀察事件</small><strong id="event-count">0</strong></div></div><p class="prototype">預錄影片教學示範・不作為安全監測</p>';
}
function settingsPanel(){return `<details class="settings"><summary>教師設定與判斷參數</summary><form id="settings"><div class="parameter-grid"><div><label for="visibility">最低可見度（0–1）</label><input id="visibility" name="visibility" type="number" min="0.1" max="1" step="0.05" value="${p.visibility}" required></div>${stage==='count'?`<div><label for="side">觀察哪隻手</label><select id="side" name="side"><option value="left" ${p.side==='left'?'selected':''}>左手（使用者）</option><option value="right" ${p.side==='right'?'selected':''}>右手（使用者）</option></select></div>${[['up','抬起門檻（度）',50,170,1],['down','放下門檻（度）',5,80,1],['hold','最短持續（毫秒）',100,2000,100],['smooth','平均幀數',1,15,1]].map(([id,label,min,max,step])=>`<div><label for="${id}">${label}</label><input id="${id}" name="${id}" type="number" min="${min}" max="${max}" step="${step}" value="${p[id]}" required></div>`).join('')}`:''}${stage==='still'?`<div><label for="seconds">未動多久提醒（秒）</label><input id="seconds" name="seconds" type="number" min="5" max="3600" value="${p.seconds}" required></div><div><label for="motion">移動門檻／肩寬</label><input id="motion" name="motion" type="number" min="0.02" max="0.5" step="0.01" value="${p.motion}" required></div><div><label for="cancel">取消窗（秒）</label><input id="cancel" name="cancel" type="number" min="3" max="30" value="${p.cancel}" required></div>`:''}</div><label class="checkbox"><input id="voice" type="checkbox" ${p.voice?'checked':''}>語音報數／提醒</label><p class="hint">${stage==='count'?'抬手角度：髖－肩－肘，肩膀為頂點。另顯示肩－肘－腕角度。先放下 → 抬起 → 放下才加一次；追蹤中斷後重新開始。':'追蹤中斷時，停止並重設持續時間。'}</p><button class="secondary full" type="submit">套用設定，重新開始判斷</button></form></details>`;}
function logPanel(){return `<details class="settings"><summary>課堂測試紀錄</summary><p class="hint">比較距離、光線、遮擋，記下誤判與修正。</p><form id="observation"><label for="condition">測試情況</label><select id="condition"><option>正常環境</option><option>光線不足</option><option>距離太遠</option><option>身體被遮擋</option><option>換人測試</option><option>誤判／漏判</option></select><label for="memo">觀察與修正</label><textarea id="memo" placeholder="例如：坐遠後手腕消失，移近再測。" required></textarea><button class="secondary full">記下觀察</button></form><p class="save-state" id="log-count"></p><ul class="logs" id="logs"></ul><button class="secondary full" id="export">下載測試紀錄 CSV</button></details>`;}
function bind(){main.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>go(b.dataset.stage));const on=(id,event,fn)=>{if($(id))$(id).addEventListener(event,fn);};on('start','click',startCamera);on('stop','click',()=>{stopMedia();$('tracking').textContent='已停止，攝影機已關閉。';});on('reset-count','click',()=>{counter=new MotionLogic.Counter(p);$('count').innerHTML='0 <span>次</span>';$('action').textContent='先放下手，再抬起。';});on('cancel-alert','click',()=>{still.cancel(lastClock,lastPoints);$('alert').hidden=true;log('取消提醒','使用者在取消窗按下取消');});on('settings','submit',e=>{e.preventDefault();const next={...p};new FormData(e.target).forEach((value,key)=>next[key]=key==='side'?value:Number(value));next.voice=$('voice').checked;if(next.down>=next.up){notice('放下門檻必須小於抬起門檻。');return;}p=next;resetLogic();if($('count'))$('count').innerHTML='0 <span>次</span>';if($('idle'))$('idle').innerHTML='0 <span>秒</span>';if($('alert'))$('alert').hidden=true;log('修改參數','教師套用設定');notice('設定已套用，動作判斷重新開始。');});on('observation','submit',e=>{e.preventDefault();log($('condition').value,$('memo').value.trim());$('memo').value='';notice('已記下觀察，可下載 CSV。');});on('export','click',exportCSV);on('file','change',loadVideo);on('play','click',()=>{if($('video').paused)$('video').play().catch(()=>notice('影片無法播放，請改用瀏覽器支援的影片。'));else $('video').pause();});refreshLogs();}
async function loadModel(){if(detector)return detector;if(!modelPromise)modelPromise=(async()=>{const {FilesetResolver,PoseLandmarker}=await import('./vendor/vision_bundle.mjs');const vision=await FilesetResolver.forVisionTasks('./vendor/wasm');detector=await PoseLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'./vendor/pose_landmarker_lite.task',delegate:'CPU'},runningMode:'VIDEO',numPoses:1,minPoseDetectionConfidence:.5,minPosePresenceConfidence:.5,minTrackingConfidence:.5});return detector;})().catch(e=>{modelPromise=null;throw e;});return modelPromise;}
async function startCamera(){if(running||loading)return;if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){notice('攝影機需要 HTTPS 或本機 localhost 網址，請不要直接雙擊 HTML 使用攝影機。');return;}loading=true;const token=++session;$('start').disabled=true;$('tracking').textContent='正在準備辨識，請稍候…';try{await loadModel();if(token!==session)return;const acquired=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});if(token!==session){acquired.getTracks().forEach(t=>t.stop());return;}stream=acquired;$('video').srcObject=stream;await $('video').play();if(token!==session)return;loading=false;resetLogic();if($('count'))$('count').innerHTML='0 <span>次</span>';if($('idle'))$('idle').innerHTML='0 <span>秒</span>';running=true;lastFrame=-1;lastInference=0;$('camera').classList.add('running');$('stop').disabled=false;$('tracking').textContent='請讓上半身完整進入鏡頭。';log('開始攝影機','固定鏡頭、單人上半身辨識');loop();}catch(e){if(token!==session)return;stopMedia();$('tracking').textContent='尚未開始';notice(e.name==='NotAllowedError'?'攝影機權限未開啟，請允許後重試。':e.name==='NotFoundError'?'找不到攝影機，請接上攝影機後重試。':'無法啟動辨識或攝影機。請用本機伺服器開啟並確認 vendor 檔案完整。');}}
let videoEvents=0;
async function loadVideo(e){const file=e.target.files[0];if(!file)return;stopMedia();if(fileURL)URL.revokeObjectURL(fileURL);const token=++session;loading=true;$('tracking').textContent='正在載入影片辨識…';try{await loadModel();if(token!==session)return;fileURL=URL.createObjectURL(file);const v=$('video');v.src=fileURL;v.muted=true;v.onloadeddata=()=>{if(token!==session)return;loading=false;videoEvents=0;$('event-count').textContent='0';$('camera').classList.add('running');$('play').disabled=false;$('tracking').textContent='影片已就緒，按播放開始觀察。';};v.onplay=()=>{if(token!==session)return;resetLogic();running=true;lastFrame=-1;$('play').textContent='暫停';loop();};v.onpause=()=>{if(token!==session)return;running=false;cancelAnimationFrame(frameId);resetLogic();$('play').textContent='播放／繼續';$('tracking').textContent=v.ended?'影片已結束':'影片已暫停';};v.onseeking=()=>{if(token!==session)return;resetLogic();lastFrame=-1;};v.onerror=()=>{if(token!==session)return;loading=false;$('play').disabled=true;notice('無法播放這段影片，請改用 MP4（H.264）格式。');};v.load();}catch{loading=false;notice('模型載入失敗，請確認本機伺服器與 vendor 檔案。');}}
function loop(){cancelAnimationFrame(frameId);if(!running)return;const v=$('video');const now=performance.now();if(v.readyState>=2&&v.currentTime!==lastFrame&&now-lastInference>=90){lastInference=now;lastFrame=v.currentTime;try{const result=detector.detectForVideo(v,now);const t=stage==='video'?v.currentTime*1000:now;if(lastClock>=0&&(t-lastClock>1500||t<lastClock))resetLogic();lastClock=t;processPose(result.landmarks[0]||null,t,v.videoWidth/v.videoHeight);draw(result.landmarks[0]||null);}catch(e){stopMedia();notice('辨識暫停，請重新開啟。若持續失敗，請換用 Chrome 或 Edge。');return;}}frameId=requestAnimationFrame(loop);}
const trackedIds=[11,12,13,14,15,16,23,24];
function processPose(raw,t,aspect=1){const arm=p.side==='left'?[11,13,15,23]:[12,14,16,24];const ids=stage==='count'?arm:stage==='video'?[11,12,23,24]:trackedIds;const visibility=raw?Math.min(...ids.map(i=>raw[i]?.visibility||0)):0;tracking=!!raw&&visibility>=p.visibility;const quality=$('quality');if(quality)quality.textContent=raw?`${Math.round(visibility*100)}%`:'—';if($('pose-status'))$('pose-status').textContent=tracking?'清楚':'調整位置';if(!tracking){$('tracking').textContent=raw?'部分身體看不清楚，請調整位置。':'沒有看見完整的人，請進入鏡頭。';if(wasTracking===true)log('追蹤中斷','遮擋或可見度不足，停止計次及計時');wasTracking=false;counter.update(null,t);still.reset();fall.reset();lastPoints=null;if($('idle'))$('idle').innerHTML='0 <span>秒</span>';if($('progress'))$('progress').value=0;if($('alert'))$('alert').hidden=true;if($('arm-angle')){$('arm-angle').textContent='—';$('elbow-angle').textContent='—';$('action').textContent='看清楚後，請先放下手。';}if($('tilt'))$('tilt').textContent='—';return;}
 wasTracking=true;$('tracking').textContent='看得清楚，可以繼續。';const pts=raw.map(x=>({x:x.x*aspect,y:x.y}));
 if(stage==='count'){const [s,e,w,h]=arm;const a=MotionLogic.angle(pts[h],pts[s],pts[e]),elbow=MotionLogic.angle(pts[s],pts[e],pts[w]);const added=counter.update(a,t);$('arm-angle').textContent=a===null?'—':`${Math.round(counter.angle)}°`;$('elbow-angle').textContent=elbow===null?'—':`${Math.round(elbow)}°`;$('action').textContent={"need-down":'先把手放下，準備開始。',ready:'準備好了，慢慢抬起手。',raised:'抬起了，再慢慢放下。'}[counter.phase];if(added){$('count').innerHTML=`${counter.count} <span>次</span>`;speak(`${counter.count}次`);log('完成舉手',`完整抬起放下一次，累計 ${counter.count} 次`);}}
 if(stage==='still'){lastPoints=trackedIds.map(i=>pts[i]);lastScale=Math.hypot(pts[11].x-pts[12].x,pts[11].y-pts[12].y);const result=still.update(lastPoints,lastScale,t);$('idle').innerHTML=`${Math.floor(still.elapsed)} <span>秒</span>`;$('progress').max=p.seconds;$('progress').value=still.elapsed;if(result.state==='pending'){$('alert').hidden=false;$('alert-title').textContent='要不要稍微動一動？';$('alert-text').textContent=`${Math.ceil(result.left)} 秒內可以取消；動作明顯改變也會取消。`;}else if(result.state==='event'){$('alert').hidden=false;$('alert-title').textContent='休息一下，換個姿勢';$('alert-text').textContent='已完成一次提醒。可以按取消，重新開始觀察。';speak('休息一下，可以換個姿勢。');log('未動提醒',`持續 ${p.seconds} 秒，加上 ${p.cancel} 秒取消窗`);}else if(result.state==='moving'||result.state==='waiting'){$('alert').hidden=true;}}
 if(stage==='video'){const shoulder={x:(pts[11].x+pts[12].x)/2,y:(pts[11].y+pts[12].y)/2};const hip={x:(pts[23].x+pts[24].x)/2,y:(pts[23].y+pts[24].y)/2};const tilt=Math.atan2(Math.abs(shoulder.x-hip.x),Math.abs(shoulder.y-hip.y))*180/Math.PI;$('tilt').textContent=`${Math.round(tilt)}°`;if(fall.update({x:0,y:(shoulder.y+hip.y)/2},tilt,t)){videoEvents++;$('event-count').textContent=videoEvents;log('影片候選事件',`影片 ${Math.round(t/1000)} 秒：快速下移＋軀幹傾斜，需人工確認`);notice('標記一個候選事件，請人工確認是否為誤判。');}}
}
function draw(points){const c=$('overlay'),v=$('video');if(c.width!==v.videoWidth||c.height!==v.videoHeight){c.width=v.videoWidth;c.height=v.videoHeight;}const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);if(!points)return;const connections=[[11,12],[11,13],[13,15],[12,14],[14,16],[11,23],[12,24],[23,24]];ctx.lineWidth=4;ctx.strokeStyle='#39efc4';for(const[a,b]of connections){if(points[a].visibility<p.visibility||points[b].visibility<p.visibility)continue;ctx.beginPath();ctx.moveTo(points[a].x*c.width,points[a].y*c.height);ctx.lineTo(points[b].x*c.width,points[b].y*c.height);ctx.stroke();}for(const i of trackedIds){if(points[i].visibility<p.visibility)continue;ctx.fillStyle='#ffcf48';ctx.beginPath();ctx.arc(points[i].x*c.width,points[i].y*c.height,6,0,Math.PI*2);ctx.fill();}}
function exportCSV(){const cell=s=>'"'+String(s??'').replace(/^[=+@-]/,"'").replace(/"/g,'""')+'"';const rows=[['時間','活動','類型','觀察','參數'],...observations.map(x=>[x.time,titles[x.stage]||'首頁',x.kind,x.note,JSON.stringify(x.parameters)])];const blob=new Blob(['\uFEFF'+rows.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='動動手_測試紀錄.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&stage!=='home'){stopMedia();if($('tracking'))$('tracking').textContent='頁面已暫停，回來後請重新開始。';}});
window.addEventListener('pagehide',stopMedia);
render();
