const main=document.getElementById('main'),$=id=>document.getElementById(id);
const catalog=[
 ['apple','00','剝蘋果皮','左右滑動，熟悉操作','apple0.png'],
 ['fish','01','找小魚','看看花紋，找出小魚','fish1.png'],
 ['fruit','02','水果歸位','把水果放回相同的籃子','hero.png'],
 ['puzzle','03','魚盤拼圖','沿著虛線，把盤子拼回來','plate.png'],
 ['laundry','04','收衣服','移動籃子，接住五件衣物','hero.png'],
 ['mosquito','05','噴蚊子','按住噴霧罐，對準蚊子','mosquito.png']
];
const instructions={apple:'手指按住向左或向右滑，剝下一條。放開，再滑一次。',fish:'請找有條紋的小魚。',fruit:'拖動水果到相同的籃子。也可以先點水果，再點籃子。',puzzle:'拖動碎片到相同的虛線位置。也可以先點碎片，再點位置。',laundry:'按開始後，上下左右移動籃子，接住掉下來的衣服。',mosquito:'按住右側噴霧罐才會噴氣，上下拖動對準蚊子；放開就停止。'};
const imgs=new Map();let active=null,g=null,raf=0,previous=0,loadGeneration=0,layout=null,canvas=null,ctx=null,pointer=null,keys=new Set(),buzz=null;
const W=500,H=700,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function message(s){$('notice').textContent=s;}
function speak(s){if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(s);u.lang='zh-TW';u.rate=.85;speechSynthesis.speak(u);}else message(s);}
function asset(game,name){return `assets/${game}/${name}`;}
function image(game,name){return imgs.get(asset(game,name));}
async function load(game,names){await Promise.all(names.map(name=>{const path=asset(game,name);if(imgs.has(path))return;return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{imgs.set(path,im);resolve();};im.onerror=reject;im.src=path;});}));}
function clean(){loadGeneration++;cancelAnimationFrame(raf);keys.clear();pointer=null;if(g)g.spraying=false;if(buzz){buzz.pause();buzz=null;}if('speechSynthesis'in window)speechSynthesis.cancel();}
function menu(){clean();active=null;g=null;message('');main.innerHTML=`<div class="eyebrow">先暖身，再慢慢挑戰。</div><h1>動動腦</h1><p class="lead">六個活動，選一個開始。</p><div class="game-menu">${catalog.map(([id,n,t,d,file])=>`<button class="game-card" data-game="${id}"><img src="${asset(id,file)}" alt=""><span><em>${n} ${id==='apple'?'操作暖身':''}</em><strong>${t}</strong><small>${d}</small></span></button>`).join('')}</div><details class="teacher"><summary>教師用：原始 App Inventor 專案</summary><p class="hint">網頁已用 JavaScript 重寫玩法；.aia 是保留的積木教材，不是在網頁內執行。</p>${catalog.map(([id,n,t])=>`<a href="../app-inventor/${id}.aia" download>${n} ${t} · 下載 .aia</a>`).join('')}</details>`;main.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>openGame(b.dataset.game));}
$('home').onclick=menu;
async function openGame(id){clean();active=id;message('正在準備活動…');const generation=loadGeneration;g={mode:'ready',count:0,session:'brain-'+Date.now()+'-'+Math.random(),selected:null,spraying:false,completeSaved:false};const names={apple:[...Array.from({length:5},(_,i)=>`apple${i}.png`),'apple_core.png'],fish:['fish1.png','fish2.png','fish3.png'],fruit:[...Array.from({length:3},(_,i)=>`fruit${i}.png`),...Array.from({length:3},(_,i)=>`basket${i}.png`)],puzzle:['plate.png','guide.png',...Array.from({length:6},(_,i)=>`piece${i}.png`)],laundry:['basket.png',...Array.from({length:5},(_,i)=>`cloth${i}.png`)],mosquito:['spray.png','mosquito.png','mosquito_dizzy.png']}[id];try{await load(id,names);if(id==='puzzle'&&!layout){const r=await fetch('assets/puzzle/layout.json');if(!r.ok)throw Error('layout');layout=await r.json();}if(generation!==loadGeneration)return;renderGame();message('');if(id==='fish'){g.mode='running';g.round=0;g.solved=false;showFish();}else{initState();draw();}}catch{if(generation===loadGeneration)message('素材無法載入。請保留完整資料夾，並使用本機伺服器開啟。');}}
function renderGame(){const title=catalog.find(x=>x[0]===active)[2];main.innerHTML=`<div class="game-top"><h1>${title}</h1><button class="quiet" id="sound">♫ 聽說明</button></div><p class="instruction" id="instruction">${instructions[active]}</p><div class="game-score" id="score">${active==='fish'?'第 1 / 3 題':'準備好了，就開始吧。'}</div>${active==='fish'?'<div class="fish-options" id="fish-options"></div><button id="next" class="primary full" hidden>下一題 →</button>':'<canvas class="board" id="board" width="500" height="700" tabindex="0" aria-label="'+title+'遊戲區"></canvas><div class="controls"><button class="primary" id="start">開始</button><button class="secondary" id="pause" disabled>暫停</button></div>'}${active==='mosquito'?'<button class="primary full spray-button" id="spray" aria-pressed="false">按住噴霧</button><div class="direction-pad"><button data-dir="up">↑ 向上</button><button data-dir="down">↓ 向下</button></div><button class="quiet full" id="finish-round">結束本回合</button><p class="key-tip">也可用 ↑ ↓ 移動，按住空白鍵噴霧。泡泡只是效果，不會額外加分。</p>':''}${active==='laundry'?'<div class="direction-pad"><button data-dir="left">←</button><button data-dir="up">↑</button><button data-dir="down">↓</button><button data-dir="right">→</button></div><p class="key-tip">也可用方向鍵移動籃子。沒接到的同一件會再掉一次。</p>':''}${active==='puzzle'?'<details><summary>看看完整的盤子</summary><img class="plate-reference" src="assets/puzzle/plate.png" alt="完整的臺灣紅鯉魚盤"></details>':''}${active==='apple'?'<p class="key-tip">電腦也可以聚焦遊戲區後按左／右方向鍵。</p>':''}<p class="status" id="feedback" role="status"></p><section class="completion" id="complete" hidden></section>`;
$('sound').onclick=()=>speak($('instruction').textContent);if(active==='fish')return;canvas=$('board');ctx=canvas.getContext('2d');$('start').onclick=start;$('pause').onclick=togglePause;canvas.onpointerdown=down;canvas.onpointermove=move;canvas.onpointerup=up;canvas.onpointercancel=cancelPointer;canvas.onlostpointercapture=()=>{pointer=null;setSpray(false);};if($('spray')){$('spray').onpointerdown=e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);setSpray(true);};$('spray').onpointerup=() =>setSpray(false);$('spray').onpointercancel=()=>setSpray(false);$('spray').onlostpointercapture=()=>setSpray(false);$('finish-round').onclick=()=>{if(g.mode==='running'||g.mode==='paused')finish(g.count>=5);};}main.querySelectorAll('[data-dir]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.dir);};b.onpointerup=()=>keys.delete(b.dataset.dir);b.onpointercancel=()=>keys.delete(b.dataset.dir);b.onlostpointercapture=()=>keys.delete(b.dataset.dir);});}
function initState(){g.count=0;g.selected=null;g.objects=[];g.spraying=false;g.stun=0;g.hitDuration=0;g.time=0;g.skin=0;g.queue=[];g.falling=null;g.basket={x:165,y:575,w:170,h:102};g.can={x:390,y:340,w:94,h:160};g.mosquito={x:200,y:150,w:70,h:84,vy:180};
if(active==='fruit'){g.objects=Array.from({length:3},(_,i)=>({id:i,x:35+i*165,y:240,w:100,h:100,homeX:35+i*165,homeY:240,done:false}));}
if(active==='puzzle'){g.objects=layout.bounds.map((b,i)=>{const slot=layout.slots[i],scale=.32;return{id:i,x:65+(slot%2)*245,y:335+Math.floor(slot/2)*116,w:(b[2]-b[0])*scale,h:(b[3]-b[1])*scale,homeX:65+(slot%2)*245,homeY:335+Math.floor(slot/2)*116,done:false,tx:25+b[0]*.5,ty:35+b[1]*.5,tw:(b[2]-b[0])*.5,th:(b[3]-b[1])*.5};});}
if(active==='laundry'){g.queue=[0,1,2,3,4].sort(()=>Math.random()-.5);g.hanging=[true,true,true,true,true];}
}
function start(){cancelAnimationFrame(raf);keys.clear();pointer=null;initState();g.mode='running';g.session='brain-'+Date.now()+'-'+Math.random();g.completeSaved=false;$('complete').hidden=true;$('start').textContent='重新開始';$('pause').disabled=false;$('pause').textContent='暫停';$('feedback').textContent='';if(active==='laundry')spawnCloth();previous=performance.now();updateScore();raf=requestAnimationFrame(frame);canvas.focus({preventScroll:true});}
function updateScore(){const total={apple:5,fruit:3,puzzle:6,laundry:5,mosquito:5}[active];$('score').textContent=active==='mosquito'?`噴中 ${g.count} 隻 · ${g.count*5} 分`:`完成 ${g.count} / ${total}`;}
function togglePause(){if(!['running','paused'].includes(g.mode))return;g.mode=g.mode==='running'?'paused':'running';keys.clear();setSpray(false);$('pause').textContent=g.mode==='paused'?'繼續':'暫停';draw();}
function finish(completed=true){if(g.mode==='done')return;g.mode='done';cancelAnimationFrame(raf);keys.clear();setSpray(false);if($('pause'))$('pause').disabled=true;const title=catalog.find(x=>x[0]===active)[2];const detail=active==='mosquito'?`噴中 ${g.count} 隻，${g.count*5} 分`:`完成 ${g.count} 項`;if(!g.completeSaved){g.completeSaved=recordParticipation({id:g.session,kind:'brain',activity:title,completed,details:detail});}const box=$('complete');box.hidden=false;box.innerHTML=`<h2>${completed?'完成了！':'這一回合結束了'}</h2><p>${detail}，休息一下也很好。</p>${!g.completeSaved?'<p>瀏覽器未能保存成果。</p>':''}${active==='apple'?'<img src="assets/apple/apple_core.png" alt="剝完後的蘋果核心" style="width:100%;max-height:220px;object-fit:contain">':''}<button class="primary full" id="again">再玩一次</button><a class="secondary full" href="../index.html#results">看我的成果 →</a><button class="quiet full" id="choose">選其他活動</button>`;$('again').onclick=()=>active==='fish'?openGame('fish'):start();$('choose').onclick=menu;if(active!=='fish')draw();box.scrollIntoView({block:'nearest',behavior:'auto'});}
function showFish(){const q=['請找有條紋的小魚。','請找有圓點的小魚。','請找沒有花紋的小魚。'];$('instruction').textContent=q[g.round];$('score').textContent=`第 ${g.round+1} / 3 題`;$('feedback').textContent='';$('next').hidden=true;g.solved=false;const order=[0,1,2].sort(()=>Math.random()-.5);$('fish-options').innerHTML=order.map(i=>`<button data-fish="${i}" aria-label="${['條紋','圓點','沒有花紋'][i]}小魚"><img src="assets/fish/fish${i+1}.png" alt="${['條紋','圓點','沒有花紋'][i]}小魚"></button>`).join('');document.querySelectorAll('[data-fish]').forEach(b=>b.onclick=()=>{if(g.solved||g.mode!=='running')return;if(Number(b.dataset.fish)===g.round){g.solved=true;g.count++;b.classList.add('correct');$('feedback').textContent='找到了！';if(g.count===3)finish();else{$('next').hidden=false;$('next').onclick=()=>{g.round++;showFish();};}}else $('feedback').textContent='再看看花紋，慢慢找。';});}
function pos(e){const b=canvas.getBoundingClientRect();return{x:(e.clientX-b.left)*W/b.width,y:(e.clientY-b.top)*H/b.height};}
function inside(p,o){return p.x>=o.x&&p.x<=o.x+o.w&&p.y>=o.y&&p.y<=o.y+o.h;}
function down(e){if(g.mode!=='running')return;e.preventDefault();const p=pos(e);canvas.setPointerCapture(e.pointerId);pointer={...p,startX:p.x,startY:p.y,used:false,moved:false,obj:null};if(active==='apple')return;if(active==='laundry'){g.basket.x=clamp(p.x-g.basket.w/2,0,W-g.basket.w);g.basket.y=clamp(p.y-g.basket.h/2,130,H-g.basket.h);return;}if(active==='mosquito'){if(inside(p,g.mosquito)){buzz=new Audio('assets/mosquito/touch_buzz.wav');buzz.play().catch(()=>{});}if(p.x>=g.can.x-20){g.can.y=clamp(p.y-35,30,H-g.can.h);pointer.can=true;setSpray(true);}return;}
const object=g.objects.slice().reverse().find(o=>!o.done&&inside(p,o));if(object){g.selected=object.id;pointer.obj=object;pointer.dx=p.x-object.x;pointer.dy=p.y-object.y;$('feedback').textContent='已選取，拖曳或點一下對應位置。';}else if(g.selected!==null){dropAt(g.objects[g.selected],p,true);pointer=null;}}
function move(e){if(!pointer||g.mode!=='running')return;const p=pos(e);if(Math.hypot(p.x-pointer.startX,p.y-pointer.startY)>8)pointer.moved=true;if(active==='apple'){if(!pointer.used&&Math.abs(p.x-pointer.startX)>=40&&Math.abs(p.x-pointer.startX)>=Math.abs(p.y-pointer.startY)){pointer.used=true;g.skin++;g.count++;updateScore();}return;}if(active==='laundry'){g.basket.x=clamp(p.x-g.basket.w/2,0,W-g.basket.w);g.basket.y=clamp(p.y-g.basket.h/2,130,H-g.basket.h);}if(active==='mosquito'&&pointer.can)g.can.y=clamp(p.y-35,30,H-g.can.h);if(pointer.obj){pointer.obj.x=clamp(p.x-pointer.dx,0,W-pointer.obj.w);pointer.obj.y=clamp(p.y-pointer.dy,0,H-pointer.obj.h);}}
function up(e){if(!pointer)return;const p=pos(e);if(active==='apple'&&g.skin>=5)finish();else if(pointer.obj&&pointer.moved)dropAt(pointer.obj,p,false);pointer=null;setSpray(false);}
function cancelPointer(){if(pointer?.obj){pointer.obj.x=pointer.obj.homeX;pointer.obj.y=pointer.obj.homeY;}pointer=null;setSpray(false);}
function dropAt(o,p,click){if(!o||o.done)return;let success=false;if(active==='fruit'){const target={x:8+o.id*165,y:515,w:155,h:145};success=inside(p,target)||(inside({x:o.x+o.w/2,y:o.y+o.h/2},target)&&!click);if(success){o.x=target.x+27;o.y=target.y+15;}}else{const target={x:o.tx-18,y:o.ty-18,w:o.tw+36,h:o.th+36};success=click?inside(p,target):Math.hypot(o.x+o.w/2-(o.tx+o.tw/2),o.y+o.h/2-(o.ty+o.th/2))<85;if(success){o.x=o.tx;o.y=o.ty;o.w=o.tw;o.h=o.th;}}
if(success){o.done=true;g.selected=null;g.count++;updateScore();$('feedback').textContent='放對了！';if(g.count===(active==='fruit'?3:6))finish();}else{o.x=o.homeX;o.y=o.homeY;$('feedback').textContent='再看看位置，慢慢試。';}}
function spawnCloth(){if(!g.queue.length){finish();return;}const id=g.queue.shift();g.hanging[id]=false;g.falling={id,x:15+id*98,y:125,w:75,h:96};}
function setSpray(on){if(g)g.spraying=!!on&&g.mode==='running';if($('spray'))$('spray').setAttribute('aria-pressed',String(!!g?.spraying));}
function step(dt){g.time+=dt;if(active==='laundry'){const b=g.basket,spd=440;if(keys.has('left'))b.x-=spd*dt;if(keys.has('right'))b.x+=spd*dt;if(keys.has('up'))b.y-=spd*dt;if(keys.has('down'))b.y+=spd*dt;b.x=clamp(b.x,0,W-b.w);b.y=clamp(b.y,130,H-b.h);const c=g.falling;if(c){const old=c.y+c.h;c.y+=315*dt;const horizontal=c.x+c.w>b.x&&c.x<b.x+b.w;const overlap=c.y+c.h>=b.y&&c.y<=b.y+b.h*.55;if(horizontal&&overlap&&old<=b.y+b.h){g.count++;updateScore();$('feedback').textContent='接到了！';spawnCloth();}else if(c.y>H){c.y=125;c.x=15+c.id*98;$('feedback').textContent='沒關係，同一件再接一次。';}}}
if(active==='mosquito'){if(keys.has('up'))g.can.y-=360*dt;if(keys.has('down'))g.can.y+=360*dt;g.can.y=clamp(g.can.y,30,H-g.can.h);if(g.stun>0){g.stun-=dt;if(g.stun<=0){if(g.count>=5){finish();return;}g.mosquito.x=55+Math.random()*230;g.mosquito.y=35;g.hitDuration=0;}return;}const m=g.mosquito;m.y+=m.vy*dt;m.x=clamp(m.x+Math.sin(g.time*1.7)*25*dt,30,300);if(m.y<20){m.y=20;m.vy=Math.abs(m.vy);}if(m.y>H-m.h-20){m.y=H-m.h-20;m.vy=-Math.abs(m.vy);}const nozzleY=g.can.y+18;const hit=g.spraying&&m.x+m.w/2<g.can.x&&Math.abs(m.y+m.h/2-nozzleY)<50;g.hitDuration=hit?g.hitDuration+dt:0;if(g.hitDuration>=.13){g.count++;g.stun=.7;updateScore();$('feedback').textContent='噴中了！＋5 分';}}
}
function imgFit(im,x,y,w,h){if(!im)return;const s=Math.min(w/im.width,h/im.height);ctx.drawImage(im,x+(w-im.width*s)/2,y+(h-im.height*s)/2,im.width*s,im.height*s);}
function draw(){if(!ctx||!g)return;ctx.clearRect(0,0,W,H);ctx.fillStyle=active==='mosquito'?'#4c6285':active==='apple'?'#153e48':'#e3efed';ctx.fillRect(0,0,W,H);
if(active==='apple'){imgFit(image('apple',g.skin>=5?'apple_core.png':`apple${g.skin}.png`),0,0,W,H);}
if(active==='fruit'){for(let i=0;i<3;i++){imgFit(image('fruit',`basket${i}.png`),8+i*165,515,155,145);}}
if(active==='puzzle'){ctx.drawImage(image('puzzle','guide.png'),25,35,450,282.5);}
if(active==='fruit'||active==='puzzle'){for(const o of g.objects){ctx.drawImage(image(active,active==='fruit'?`fruit${o.id}.png`:`piece${o.id}.png`),o.x,o.y,o.w,o.h);if(g.selected===o.id&&!o.done){ctx.strokeStyle='#ae4b21';ctx.lineWidth=4;ctx.setLineDash([7,5]);ctx.strokeRect(o.x-4,o.y-4,o.w+8,o.h+8);ctx.setLineDash([]);}}}
if(active==='laundry'){ctx.fillStyle='#ebd9b9';ctx.fillRect(0,630,W,70);ctx.strokeStyle='#826443';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,40);ctx.lineTo(W,40);ctx.stroke();for(let i=0;i<5;i++){const x=15+i*98;ctx.fillStyle='#ac7d3e';ctx.fillRect(x+32,30,9,26);if(g.hanging[i])imgFit(image('laundry',`cloth${i}.png`),x,48,75,96);}if(g.falling)imgFit(image('laundry',`cloth${g.falling.id}.png`),g.falling.x,g.falling.y,g.falling.w,g.falling.h);imgFit(image('laundry','basket.png'),g.basket.x,g.basket.y,g.basket.w,g.basket.h);}
if(active==='mosquito'){const can=g.can;if(g.mode==='running'&&g.spraying){for(let i=0;i<45;i++){const f=(g.time*1.3+i/45)%1,x=can.x-f*(W+60),y=can.y+18+Math.sin(i*6.7)*f*250,r=8+f*30;ctx.fillStyle=`rgba(255,255,255,${.65*(1-f)})`;ctx.strokeStyle=`rgba(226,243,255,${.9*(1-f)})`;ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill();ctx.stroke();}}imgFit(image('mosquito','spray.png'),can.x,can.y,can.w,can.h);const m=g.mosquito;imgFit(image('mosquito',g.stun>0?'mosquito_dizzy.png':'mosquito.png'),m.x,m.y,m.w,m.h);}
if(g.mode==='paused'){ctx.fillStyle='#fffdf7dc';ctx.fillRect(0,0,W,H);ctx.fillStyle='#16344b';ctx.font='bold 32px sans-serif';ctx.textAlign='center';ctx.fillText('休息一下，按「繼續」',W/2,H/2);}
}
function frame(t){if(!g||active==='fish')return;const dt=Math.min((t-previous)/1000,.05);previous=t;if(g.mode==='running')step(dt);draw();if(g.mode!=='done')raf=requestAnimationFrame(frame);}
document.addEventListener('keydown',e=>{if(!g||g.mode!=='running'||['INPUT','TEXTAREA'].includes(e.target.tagName))return;const mapping={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'};if(mapping[e.key]){e.preventDefault();if(active==='apple'&&!e.repeat&&['ArrowLeft','ArrowRight'].includes(e.key)){g.skin++;g.count++;updateScore();if(g.count>=5)finish();}else keys.add(mapping[e.key]);}if(e.code==='Space'&&active==='mosquito'){e.preventDefault();setSpray(true);}});
document.addEventListener('keyup',e=>{keys.delete({ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}[e.key]);if(e.code==='Space')setSpray(false);});window.addEventListener('blur',()=>{keys.clear();setSpray(false);if(g?.mode==='running'&&active!=='fish')togglePause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&g?.mode==='running'&&active!=='fish')togglePause();});window.addEventListener('pagehide',clean);menu();
