const main=document.getElementById('main'),notice=document.getElementById('notice');let day=localDay();
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const modules=[['01','動動腦','六個小活動，依自己的步調玩','brain','#006b69'],['02','動動手','看見動作、舉手、動一動','motion','#b04b25'],['03','生活紀錄','記喝水、飲食與走路次數','life','#246295'],['04','聊天分享','說說生活，分享今天的心情','chat','#9b3860']];
function render(){notice.textContent='';if(location.hash!=='#results'){main.innerHTML=`<div class="eyebrow">動動腦・動動手・記錄生活</div><h1>今天，想做什麼？</h1><p class="root-date">${new Date().toLocaleDateString('zh-TW',{month:'long',day:'numeric',weekday:'long'})}</p><div class="hub-cards">${modules.map(([n,t,d,url,color])=>`<a class="hub-card" href="${url}/index.html" style="--accent:${color}"><span class="num">${n}</span><span><strong>${t}</strong><small>${d}</small>${url==='chat'?'<small class="status-tag">目前為介面試用</small>':''}</span><span class="arrow">›</span></a>`).join('')}</div><a href="#results" class="result-link">我的成果</a><button class="secondary home-text-button" id="speak">♫ 聽說明</button><details class="readiness"><summary>教師說明與 App Inventor 教材</summary><p>動動腦已改寫成 JavaScript，可直接在網頁玩。原始 .aia 保留在動動腦選單下方。</p><p>動動手需攝影機與 HTTPS／localhost。聊天目前不會呼叫 LLM；生活紀錄先存在瀏覽器。</p></details>`;document.getElementById('speak').onclick=()=>say('選一個活動開始。動動腦玩遊戲，動動手練習動作，生活紀錄記下日常，聊天分享目前是介面試用。完成後可以看看我的成果。');return;}
const activity=participationFor(day),brain=activity.filter(x=>x.kind==='brain'),done=brain.filter(x=>x.completed),chat=activity.filter(x=>x.kind==='chat-demo');
const life=readSaved('daily-life-records-v1',{water:[],food:[],walk:{}}),water=life.water.filter(x=>x.day===day),food=life.food.filter(x=>x.day===day),walk=life.walk[day];
const motion=readSaved('motion-observations-v1',[]).filter(x=>localDay(new Date(x.time))===day),raises=motion.filter(x=>x.kind==='完成舉手').length,starts=motion.filter(x=>x.kind==='開始攝影機').length,reminders=motion.filter(x=>x.kind==='未動提醒').length;
main.innerHTML=`<div class="eyebrow">每一次參與，都值得記下。</div><h1>我的成果</h1><div class="date-nav"><button class="quiet" id="prev">‹ 前一天</button><input id="date" type="date" value="${day}" max="${localDay()}" aria-label="成果日期"><button class="quiet" id="next" ${day>=localDay()?'disabled':''}>後一天 ›</button></div><section class="result-card" style="--accent:#006b69"><h2>動動腦</h2><p class="total">完成 ${done.length} 回活動</p>${brain.length?`<ul>${brain.map(x=>`<li>${escapeHTML(x.activity)}：${x.completed?'完成':'參與'}${x.details?' · '+escapeHTML(x.details):''}</li>`).join('')}</ul>`:'<p class="hint">這一天還沒有活動紀錄。</p>'}<a href="brain/index.html">去玩一個活動 →</a></section><section class="result-card" style="--accent:#b04b25"><h2>動動手</h2><p class="total">舉手 ${raises} 次</p><p>開啟活動 ${starts} 次・未動提醒 ${reminders} 次</p><p class="hint">僅統計實際記錄到的動作，不代表健康評估。</p><a href="motion/index.html">動動手 →</a></section><section class="result-card" style="--accent:#246295"><h2>生活紀錄</h2><p>喝水：<strong>${water.length?water.reduce((a,x)=>a+x.amount,0)+' cc':'尚未記錄'}</strong></p><p>飲食：<strong>${food.length?food.length+' 筆':'尚未記錄'}</strong></p>${food.map(x=>`<p class="hint">${escapeHTML(x.meal)}：${x.items.map(escapeHTML).join('、')}</p>`).join('')}<p>走路：<strong>${walk?walk.count+' 次':'尚未記錄'}</strong></p><a href="life/index.html">生活紀錄 →</a></section><section class="result-card" style="--accent:#9b3860"><h2>聊天分享</h2><p class="total">介面試用 ${chat.length} 次</p><p class="hint">AI 尚未串接；只記參與，不保存對話。</p><a href="chat/index.html">聊聊天 →</a></section><button class="secondary full" id="read-results">♫ 聽成果</button><a class="result-link" href="#home">回首頁</a>`;
document.getElementById('prev').onclick=()=>change(-1);document.getElementById('next').onclick=()=>change(1);document.getElementById('date').onchange=e=>{if(e.target.value&&e.target.value<=localDay()){day=e.target.value;render();}};document.getElementById('read-results').onclick=()=>say(`這一天完成${done.length}回動動腦，舉手${raises}次。${water.length?'記錄喝水'+water.reduce((a,x)=>a+x.amount,0)+'毫升。':''}${walk?'記錄走路'+walk.count+'次。':''}`);
}
function change(delta){const d=new Date(day+'T12:00:00');d.setDate(d.getDate()+delta);day=localDay(d);render();}
function say(text){if(!('speechSynthesis'in window)){notice.textContent='此瀏覽器無法播放語音，請閱讀畫面文字。';return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='zh-TW';u.rate=.85;u.onerror=()=>notice.textContent='語音暫時無法播放，請閱讀畫面文字。';speechSynthesis.speak(u);}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});window.addEventListener('pagehide',()=>{if('speechSynthesis'in window)speechSynthesis.cancel();});render();
